### ISSUE TITLE
Supprimer une sources de données

### ISSUE THREAD

**Issue by HamzaDams** [eureka2/G6K#21]
Bonjour,
Peut-on supprimer une source de donnée car j'ai beaucoup de soucis avec je voudrais remettre au propre ?

**Comment by HamzaDams** [comment]
`Symfony\Component\Debug\Exception\FatalThrowableError: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\AbstractController::getParameter() from context 'App\G6K\Model\Simulator'
at App.G6K.Model.Simulator.loadDatabases(Simulator.php:1909)
at App.G6K.Model.Simulator.loadEntities(Simulator.php:1567)
at App.G6K.Model.Simulator.loadEmptySimulator(Simulator.php:3735)
at App.G6K.Controller.SimulatorsAdminController.runIndex(SimulatorsAdminController.php:273)
at App.G6K.Controller.SimulatorsAdminController.index(SimulatorsAdminController.php:181)
at Symfony.Component.HttpKernel.HttpKernel.handleRaw(HttpKernel.php:151)
at Symfony.Component.HttpKernel.HttpKernel.handle(HttpKernel.php:68)
at Symfony.Component.HttpKernel.Kernel.handle(Kernel.php:198)
at (main)(admin.php:37)

#0 G:\laragon\www\cartegrise\simulator\src\G6K\Model\Simulator.php(1567): App\G6K\Model\Simulator->loadDatabases(Object(SimpleXMLElement))
#1 G:\laragon\www\cartegrise\simulator\src\G6K\Model\Simulator.php(3735): App\G6K\Model\Simulator->loadEntities(Object(SimpleXMLElement), Object(SimpleXMLElement))
#2 G:\laragon\www\cartegrise\simulator\src\G6K\Controller\SimulatorsAdminController.php(273): App\G6K\Model\Simulator->loadEmptySimulator()
#3 G:\laragon\www\cartegrise\simulator\src\G6K\Controller\SimulatorsAdminController.php(181): App\G6K\Controller\SimulatorsAdminController->runIndex(Object(Symfony\Component\HttpFoundation\Request), 'new', 'create')
#4 G:\laragon\www\cartegrise\simulator\vendor\symfony\http-kernel\HttpKernel.php(151): App\G6K\Controller\SimulatorsAdminController->index(Object(Symfony\Component\HttpFoundation\Request), 'new', 'create')
#5 G:\laragon\www\cartegrise\simulator\vendor\symfony\http-kernel\HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 G:\laragon\www\cartegrise\simulator\vendor\symfony\http-kernel\Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 G:\laragon\www\cartegrise\simulator\calcul\admin.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}`
