### ISSUE TITLE
Can't install G6K : PHP Fatal error:  Uncaught Error: Class 'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' not found

### ISSUE THREAD

**Issue by plumbrcom** [eureka2/G6K#24]
Hello,

I can't install the latest version G6K.

`php -d memory_limit=-1 composer.phar create-project eureka2/g6k simulator/ 4.*`

Everything is going fine until after the .env creation :

```
Creating the ".env" file
Enter the application environment [dev or prod] (prod): 
Enter the debug mode [0 or 1] (0): 
Enter the locale [en-GB, en-US, fr-FR, ...] (en-US): fr-FR
Enter the upload directory (%kernel.project_dir%/var/uploads): 
Enter the absolute path of the pdftk executable (~): 
Enter the mailer URL (null://localhost): 
Enter the database engine [sqlite, mysql or pgsql] (sqlite): 
Enter the database version (3.15): 
Enter the database path (%kernel.project_dir%/var/data/databases/g6k.db): 
Enter the HTTP proxy url [http://user:pass@host:port] (~): 
Enter the HTTPS proxy url [https://user:pass@host:port] (~): 
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class 'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' not found in /xxx/xxx/xxx/simulator/src/Kernel.php:33
```

Do you have a hint about what is causing this error ?

Thanks 

Best regards

**Comment by eureka2** [comment]
Hi,

DoctrineCacheBundle no longer exists, can you redo the installation, I just did a new release

Best regards

**Comment by victoroliveirapt** [comment]
I have the same error today with the same command to install ! I need to wait for a new version ?

Thank you

Best Regards

**Comment by pkconcept** [comment]
Hello,
same error today when running composer installation

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class 'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' not found  in simulator/src/Kernel.php:33

[installation_trace.txt](https://github.com/eureka2/G6K/files/4379862/installation_trace.txt)

**Comment by pkconcept** [comment]
No answers... dead project ?

**Comment by eureka2** [comment]
no, the project is not dead, this issue has normally been fixed in release [4.3.6](https://github.com/eureka2/G6K/releases/tag/4.3.6)

**Comment by pkconcept** [comment]
> no, the project is not dead, this issue has normally been fixed in release [4.3.6](https://github.com/eureka2/G6K/releases/tag/4.3.6)

Tested today, same error with repo..


Creating a "eureka2/g6k" project at "./simulator"
Installing eureka2/g6k (4.3.6)
  - Installing eureka2/g6k (4.3.6): Loading from cache
Created project in /var/www/vhosts/**--**/httpdocs/api/simulator/
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 112 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.4.2): Loading from cache
  - Installing symfony/flex (v1.6.2): Loading from cache
Symfony operations: 1 recipe (b421f969b8211303a7cc232fafbd653a)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^4.3"
Package operations: 110 installs, 0 updates, 0 removals
  - Installing eureka2/acroforms (1.0.6): Loading from cache
  - Installing flow/jsonpath (0.4.0): Loading from cache
  - Installing willdurand/js-translation-bundle (2.6.6): Loading from cache
  - Installing symfony/yaml (v4.4.7): Loading from cache
  - Installing symfony/polyfill-php72 (v1.15.0): Loading from cache
  - Installing psr/link (1.0.0): Loading from cache
  - Installing symfony/web-link (v4.4.7): Loading from cache
  - Installing symfony/translation-contracts (v1.1.7): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.15.0): Loading from cache
  - Installing symfony/validator (v4.4.7): Loading from cache
  - Installing symfony/twig-bundle (v4.4.7): Loading from cache
  - Installing twig/twig (v2.12.5): Loading from cache
  - Installing psr/log (1.1.3): Loading from cache
  - Installing symfony/polyfill-php73 (v1.15.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.15.0): Loading from cache
  - Installing symfony/mime (v4.4.7): Loading from cache
  - Installing symfony/http-foundation (v4.4.7): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from cache
  - Installing symfony/event-dispatcher (v4.4.7): Loading from cache
  - Installing symfony/var-dumper (v4.4.7): Loading from cache
  - Installing symfony/debug (v4.4.7): Loading from cache
  - Installing symfony/error-handler (v4.4.7): Loading from cache
  - Installing symfony/http-kernel (v4.4.7): Loading from cache
  - Installing symfony/twig-bridge (v4.4.7): Loading from cache
  - Installing symfony/filesystem (v4.4.7): Loading from cache
  - Installing symfony/config (v4.4.7): Loading from cache
  - Installing symfony/service-contracts (v1.1.8): Loading from cache
  - Installing symfony/dependency-injection (v4.4.7): Loading from cache
  - Installing doctrine/lexer (1.0.2): Loading from cache
  - Installing egulias/email-validator (2.1.17): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.3): Loading from cache
  - Installing symfony/swiftmailer-bundle (v3.4.0): Loading from cache
  - Installing symfony/serializer (v4.4.7): Loading from cache
  - Installing symfony/inflector (v4.4.7): Loading from cache
  - Installing symfony/property-info (v4.4.7): Loading from cache
  - Installing symfony/property-access (v4.4.7): Loading from cache
  - Installing phpdocumentor/reflection-common (2.0.0): Loading from cache
  - Installing webmozart/assert (1.7.0): Loading from cache
  - Installing phpdocumentor/type-resolver (1.0.1): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.4): Loading from cache
  - Installing doctrine/annotations (1.10.1): Loading from cache
  - Installing symfony/serializer-pack (v1.0.3): Loading from cache
  - Installing symfony/var-exporter (v4.4.7): Loading from cache
  - Installing symfony/cache-contracts (v1.1.7): Loading from cache
  - Installing symfony/cache (v4.4.7): Loading from cache
  - Installing symfony/security-core (v4.4.7): Loading from cache
  - Installing symfony/security-http (v4.4.7): Loading from cache
  - Installing symfony/security-guard (v4.4.7): Loading from cache
  - Installing symfony/security-csrf (v4.4.7): Loading from cache
  - Installing symfony/security-bundle (v4.4.7): Loading from cache
  - Installing symfony/process (v4.4.7): Loading from cache
  - Installing symfony/stopwatch (v4.4.7): Loading from cache
  - Installing symfony/console (v4.4.7): Loading from cache
  - Installing zendframework/zend-eventmanager (3.2.1): Loading from cache
  - Installing zendframework/zend-code (3.4.1): Loading from cache
  - Installing ocramius/proxy-manager (2.1.1): Loading from cache
  - Installing doctrine/event-manager (1.1.0): Loading from cache
  - Installing doctrine/cache (1.10.0): Loading from cache
  - Installing doctrine/dbal (v2.9.3): Loading from cache
  - Installing doctrine/reflection (1.2.1): Loading from cache
  - Installing doctrine/collections (1.6.4): Loading from cache
  - Installing doctrine/persistence (1.3.7): Loading from cache
  - Installing doctrine/inflector (1.3.1): Loading from cache
  - Installing doctrine/common (2.12.0): Loading from cache
  - Installing doctrine/migrations (2.2.1): Loading from cache
  - Installing symfony/doctrine-bridge (v4.4.7): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing symfony/routing (v4.4.7): Loading from cache
  - Installing symfony/finder (v4.4.7): Loading from cache
  - Installing symfony/framework-bundle (v4.4.7): Loading from cache
  - Installing doctrine/doctrine-bundle (2.0.7): Loading from cache
  - Installing doctrine/doctrine-migrations-bundle (2.1.2): Loading from cache
  - Installing doctrine/instantiator (1.3.0): Loading from cache
  - Installing doctrine/orm (v2.7.2): Loading from cache
  - Installing symfony/orm-pack (v1.0.8): Loading from cache
  - Installing monolog/monolog (1.25.3): Loading from cache
  - Installing symfony/monolog-bridge (v4.4.7): Loading from cache
  - Installing symfony/monolog-bundle (v3.5.0): Loading from cache
  - Installing symfony/lock (v4.4.7): Loading from cache
  - Installing symfony/expression-language (v4.4.7): Loading from cache
  - Installing symfony/asset (v4.4.7): Loading from cache
  - Installing sensio/framework-extra-bundle (v5.5.3): Loading from cache
  - Installing myclabs/deep-copy (1.9.5): Loading from cache
  - Installing setasign/fpdi (1.6.2): Loading from cache
  - Installing mpdf/mpdf (v7.1.9): Loading from cache
  - Installing mobiledetect/mobiledetectlib (2.8.34): Loading from cache
  - Installing symfony/templating (v4.4.7): Loading from cache
  - Installing symfony/options-resolver (v4.4.7): Loading from cache
  - Installing symfony/intl (v4.4.7): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.15.0): Loading from cache
  - Installing symfony/form (v4.4.7): Loading from cache
  - Installing friendsofsymfony/user-bundle (v2.1.2): Loading from cache
  - Installing ashleydawson/simple-pagination (1.0.8): Loading from cache
  - Installing symfony/translation (v4.4.7): Loading from cache
  - Installing symfony/web-profiler-bundle (v4.4.7): Loading from cache
  - Installing symfony/profiler-pack (v1.0.4): Loading from cache
  - Installing easycorp/easy-log-handler (v1.0.9): Loading from cache
  - Installing symfony/debug-bundle (v4.4.7): Loading from cache
  - Installing symfony/debug-pack (v1.0.7): Loading from cache
  - Installing symfony/dotenv (v4.4.7): Loading from cache
  - Installing nikic/php-parser (v4.3.0): Loading from cache
  - Installing symfony/maker-bundle (v1.15.0): Loading from cache
  - Installing symfony/phpunit-bridge (v4.4.7): Loading from cache
  - Installing symfony/css-selector (v4.4.7): Loading from cache
  - Installing symfony/dom-crawler (v4.4.7): Loading from cache
  - Installing symfony/browser-kit (v4.4.7): Loading from cache
  - Installing symfony/test-pack (v1.0.6): Loading from cache
  - Installing symfony/web-server-bundle (v4.4.7): Loading from cache
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Writing lock file
Generating autoload files
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 21 recipes (b421f969b8211303a7cc232fafbd653a)
  - Configuring symfony/framework-bundle (>=4.4): From github.com/symfony/recipes:master
  - Configuring willdurand/js-translation-bundle (>=2.0): From github.com/symfony/recipes:master
  - Configuring symfony/validator (>=4.3): From github.com/symfony/recipes:master
  - Configuring symfony/twig-bundle (>=4.4): From github.com/symfony/recipes:master
  - Configuring symfony/swiftmailer-bundle (>=2.5): From github.com/symfony/recipes:master
  - Configuring doctrine/annotations (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/security-bundle (>=4.4): From github.com/symfony/recipes:master
  - Configuring symfony/console (>=4.4): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=4.2): From github.com/symfony/recipes:master
  - Configuring doctrine/doctrine-bundle (>=2.0): From github.com/symfony/recipes:master
  - Configuring doctrine/doctrine-migrations-bundle (>=1.2): From github.com/symfony/recipes:master
  - Configuring symfony/monolog-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring sensio/framework-extra-bundle (>=5.2): From github.com/symfony/recipes:master
  - Configuring friendsofsymfony/user-bundle (>=v2.1.2): From auto-generated recipe
  - Configuring symfony/translation (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/web-profiler-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring easycorp/easy-log-handler (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/debug-bundle (>=4.1): From github.com/symfony/recipes:master
  - Configuring symfony/maker-bundle (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/phpunit-bridge (>=4.3): From github.com/symfony/recipes:master
  - Configuring symfony/web-server-bundle (>=3.3): From github.com/symfony/recipes:master
> App\G6K\Composer\ScriptHandler::buildDotenv
Creating the ".env" file
Enter the application environment [dev or prod] (prod): 
Enter the debug mode [0 or 1] (0): 
Enter the locale [en-GB, en-US, fr-FR, ...] (en-US): fr-FR
Enter the upload directory (%kernel.project_dir%/var/uploads): 
Enter the absolute path of the pdftk executable (~): 
Enter the mailer URL (null://localhost): 
Enter the database engine [sqlite, mysql or pgsql] (sqlite): mysql
Enter the database name (g6k): 
Enter the database host [localhost, ...] (~): localhost
Enter the database port (~): 3306
Enter the database user (~): ******
Enter the database password (~): ******
Enter the database character set [UTF8, LATIN1, ...] (UTF8): 
Enter the HTTP proxy url [http://user:pass@host:port] (~): 
Enter the HTTPS proxy url [https://user:pass@host:port] (~): 
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class 'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' not found in /var/www/vhosts/**--**/httpdocs/api/simulator/src/Kernel.php:33
!!  Stack trace:
!!  #0 /var/www/vhosts/**--**/httpdocs/api/simulator/vendor/symfony/http-kernel/Kernel.php(449): App\Kernel->registerBundles()
!!  #1 /var/www/vhosts/**--**/httpdocs/api/simulator/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /var/www/vhosts/**--**/httpdocs/api/simulator/vendor/symfony/framework-bundle/Console/Application.php(169): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /var/www/vhosts/**--**/httpdocs/api/simulator/vendor/symfony/framework-bundle/Console/Application.php(75): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /var/www/vhosts/**--**/httpdocs/api/simulator/vendor/symfony/console/Application.php(147): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),  in /var/www/vhosts/**--**/httpdocs/api/simulator/src/Kernel.php on line 33
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by eureka2** [comment]
Can you try again with the release 4.3.7 ?

**Comment by pkconcept** [comment]
version 4.37 is ok.
A little bug , for those who want to user the demo datas, the database is "demo" not the selected database when installing

Thanks! ;)
