### ISSUE TITLE
Erreur lors de l'installation sur la version Symfony Symfony 4.2 et plus

### ISSUE THREAD

**Issue by DallyRKT** [eureka2/G6K#32]
Bonjour,

Il y a une erreur d'installation depuis Symfony 4.2 et plus.

Message d'erreur :

**Fatal error:** Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in I:\xampp\htdocs\TestProg\simulator\vendor\willdurand\js-translation-bundle\DependencyInjection\Configuration.php on line 20 and at least 1 expected in I:\xampp\htdocs\TestProg\simulator\vendor\symfony\config\Definition\Builder\TreeBuilder.php:26 Stack trace: #0 I:\xampp\htdocs\TestProg\simulator\vendor\willdurand\js-translation-bundle\DependencyInjection\Configuration.php(20): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct() #1 I:\xampp\htdocs\TestProg\simulator\vendor\symfony\config\Definition\Processor.php(50): Bazinga\Bundle\JsTranslationBundle\DependencyInjection\Configuration->getConfigTreeBuilder() #2 I:\xampp\htdocs\TestProg\simulator\vendor\willdurand\js-translation-bundle\DependencyInjection\BazingaJsTranslationExtension.php(24): Symfony\Component\Config\Definition\Processor->processConfiguration(Object( in **I:\xampp\htdocs\TestProg\simulator\vendor\symfony\config\Definition\Builder\TreeBuilder.php on line 26**

**Comment by rzmendrika** [comment]
Hi, help!
How did you install it with **symfony 4.2**? thanks
