### ISSUE TITLE
Issue when trying to install g6k with php 7.4

### ISSUE THREAD

**Issue by Dexter0015** [eureka2/G6K#40]
Hi,

I Would like to install g6k on a new server on which php is running on version 7.4

Unfortunatelly I run into the following error during the installation process: 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mpdf/mpdf[v7.1.0, ..., v7.1.6] require php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your php version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf[v7.1.7, ..., v7.1.9] require php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your php version (7.4.3) does not satisfy that requirement.
    - Root composer.json requires mpdf/mpdf ^7.1 -> satisfiable by mpdf/mpdf[v7.1.0, ..., v7.1.9].
```

As indicated one the github of the mpdf project, I should use version 8.0.4 pour php 7.4 but since I use the command from the installation section : 
`composer create-project eureka2/g6k simulator/ 4.*`

which use a reciepe I believe, I don't really know how I can change the depedency version in that case.

Any idea on how I can process the installation with mpdf 8.0.4?

**Comment by eureka2** [comment]
Hi,

I think the problem is with "Composer". If you are using version 2, I suggest you use version 1 for now.

However, I changed the version of mpdf (^ 8.0) in the latest release of G6K.

**Comment by Dexter0015** [comment]
Hi,

Unfortunately, reverting to composer 1 didn't do the trick.

I choose to install version 4 of G6K because it is the master branch but I'm willing to try the last version, just one question though:

Is the version 5 stable enough to be used in production?

**Comment by eureka2** [comment]
No, version 5 is not stable
Install 4.4.6, i just release it

**Comment by eureka2** [comment]
[Release 4.4.6](https://github.com/eureka2/G6K/releases/tag/4.4.6)

**Comment by Dexter0015** [comment]
Sorry but still the same.

I run: 
`composer create-project eureka2/g6k simulator/ 4.4.6`

Tested with composer 1 or 2, and got the same result: 

```
Problem 1
    - mpdf/mpdf v7.1.9 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.8 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.7 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.6 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.5 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.4 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.3 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.2 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.1 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v7.1.0 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - Installation request for mpdf/mpdf ^7.1 -> satisfiable by mpdf/mpdf[v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.1.4, v7.1.5, v7.1.6, v7.1.7, v7.1.8, v7.1.9].
```

Composer.json in 4.4.6 doesn't have ^8.0 it seems:
`"mpdf/mpdf": "^7.1",`

**Comment by eureka2** [comment]
Sorry, I took the wrong branch when making the release.
 Can you try again with 4.4.7

**Comment by Dexter0015** [comment]
Yes the issue with the mpdf library is fixed.

Unfortunately, I got fatal error at the end of the process:

```
> App\G6K\Composer\ScriptHandler::buildDotenv
Creating the ".env" file
PHP Fatal error:  Uncaught Error: Class 'ResourceBundle' not found in /XXX/simulator/src/G6K/Composer/ScriptHandler.php:161
Stack trace:
#0 /XXX/simulator/src/G6K/Composer/ScriptHandler.php(112): App\G6K\Composer\ScriptHandler::getEnvironmentVariables()
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(322): App\G6K\Composer\ScriptHandler::buildDotenv()
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(218): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(86): Composer\EventDispatcher\EventDispatcher->doDispatch()
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(198): Composer\EventDispatcher\EventDispatcher->dispatch()
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(101): Composer\EventDispatcher\EventDispatcher->doDispatch()
#6 phar:///usr/local/bin/comp in /XXX/simulator/src/G6K/Composer/ScriptHandler.php on line 161

Fatal error: Uncaught Error: Class 'ResourceBundle' not found in /XXX/simulator/src/G6K/Composer/ScriptHandler.php:161
Stack trace:
#0 /XXX/simulator/src/G6K/Composer/ScriptHandler.php(112): App\G6K\Composer\ScriptHandler::getEnvironmentVariables()
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(322): App\G6K\Composer\ScriptHandler::buildDotenv()
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(218): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(86): Composer\EventDispatcher\EventDispatcher->doDispatch()
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(198): Composer\EventDispatcher\EventDispatcher->dispatch()
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(101): Composer\EventDispatcher\EventDispatcher->doDispatch()
#6 phar:///usr/local/bin/comp in /XXX/simulator/src/G6K/Composer/ScriptHandler.php on line 161
```

Maybe a `use` statement is missing in the `ScriptHandle.php` file?

**Comment by eureka2** [comment]
Is `intl` installed and activated with your version of PHP?

In php.ini you must have `extension=intl`

Look in the README, you will see that `intl` is a prerequisite for G6K

**Comment by Dexter0015** [comment]
My bad.

Thanks, everything works.
