### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ResourceBundle' not found in /Users/andre/simulator/src/G6K/Composer/ScriptHandler.php:161

### ISSUE THREAD

**Issue by andether89** [eureka2/G6K#49]
Salut, je tente depuis quelques jours d'installer le simulateur en local, mais aucune chance. Pouvez -vous m'aider ?
je suis débutant 

Merci 

voici l'erreure 

Fatal error: Uncaught Error: Class 'ResourceBundle' not found in /Users/andre/simulator/src/G6K/Composer/ScriptHandler.php:161
Stack trace:
#0 /Users/andre/simulator/src/G6K/Composer/ScriptHandler.php(112): App\G6K\Composer\ScriptHandler::getEnvironmentVariables(Object(Composer\Script\Event), Array)
#1 phar:///Users/andre/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(341): App\G6K\Composer\ScriptHandler::buildDotenv(Object(Composer\Script\Event))
#2 phar:///Users/andre/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(220): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('App\\G6K\\Compose...', 'buildDotenv', Object(Composer\Script\Event))
#3 phar:///Users/andre/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(87): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///Users/andre/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(200): Composer\EventDispatcher\EventDispatcher->dispatch('symfony-scripts', Object in /Users/andre/simulator/src/G6K/Composer/ScriptHandler.php on line 161
$ php -d memory_limit=-1 composer.phar create-project

**Comment by eureka2** [comment]
Is the php intl extension installed and activated ?

**Comment by andether89** [comment]
oui installée mais je serrai pas vous dire si elle est activée

**Comment by StephanSales** [comment]
Je rencontre le même problème et je confirme que dans mon cas php intl est installé et activé.
